"""YouTube Data API v3 uploader with thumbnail upload + pinned comment.

After a successful video upload this module:
  1. Sets the thumbnail (if thumbnail.jpg exists in OUT_DIR)
  2. Posts a pinned comment with scene timestamps
  3. Pins that comment via the YouTube API

All post-upload steps are non-fatal — a failure in any of them does not
abort the pipeline or count as a failed upload.
"""
from __future__ import annotations

import time
from pathlib import Path

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

from .config import YouTubeCredentials, OUT_DIR
from .quota import pick_project, record_upload
from .script_gen import Script


def _creds_from_payload(payload: dict) -> Credentials:
    # Use only the scopes granted when this refresh token was generated.
    # Requesting additional scopes (like force-ssl) during token refresh causes Google OAuth
    # to throw 'invalid_scope: Bad Request' and block the entire upload.
    scopes = payload.get("scopes")
    if not scopes:
        scopes = ["https://www.googleapis.com/auth/youtube.upload"]
    elif isinstance(scopes, str):
        scopes = [scopes]
    return Credentials(
        token=payload.get("token"),
        refresh_token=payload["refresh_token"],
        token_uri=payload.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=payload["client_id"],
        client_secret=payload["client_secret"],
        scopes=scopes,
    )


def _set_thumbnail(yt, video_id: str, thumb_path: Path, attempts: int = 4) -> None:
    """Upload thumbnail JPEG. Requires channel verification for custom thumbnails.

    Retries on transient failures: thumbnails.set is sometimes rejected with a
    generic 403 in the first few seconds after videos.insert() returns, before
    YouTube has fully registered the new video server-side — not because of a
    real permission problem. The previous version gave up after one try, so
    every video that hit this narrow window silently shipped with no
    thumbnail. Permission errors that will never resolve by waiting (missing
    scope, channel not allowed to set custom thumbnails, bad image) are
    detected and NOT retried, so this doesn't waste time on a hopeless case.
    """
    if not thumb_path.exists() or thumb_path.stat().st_size < 5000:
        print("[upload] no thumbnail file — skipping")
        return

    _PERMANENT_MARKERS = (
        "doesn't have permissions to upload and set custom video thumbnails",
        "insufficientpermissions",
        "invalidimage",
        "mediabodyrequired",
    )

    last_exc: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            media = MediaFileUpload(str(thumb_path), mimetype="image/jpeg")
            yt.thumbnails().set(videoId=video_id, media_body=media).execute()
            print(f"[upload] thumbnail uploaded: {thumb_path.name} (attempt {attempt})")
            return
        except Exception as exc:
            last_exc = exc
            msg = str(exc)
            if any(marker in msg.lower() for marker in _PERMANENT_MARKERS):
                print(
                    "[!] Thumbnail upload REJECTED — this channel is very likely not "
                    "phone-verified, or doesn't otherwise have permission to set custom "
                    "thumbnails. Verify at https://www.youtube.com/verify . "
                    f"Original error: {msg}"
                )
                return
            if attempt < attempts:
                delay = 5 * attempt  # 5s, 10s, 15s
                print(f"[!] Thumbnail upload attempt {attempt}/{attempts} failed, retrying in {delay}s: {msg}")
                time.sleep(delay)

    print(f"[!] Thumbnail upload failed after {attempts} attempts (non-fatal): {last_exc}")


def _build_timestamp_comment(script: Script, durations: list[float]) -> str:
    """Build a pinned comment with per-scene timestamps."""
    lines = [f"📚 {script.title}", ""]
    t = 0.0
    for i, (scene, dur) in enumerate(zip(script.scenes, durations)):
        minutes = int(t // 60)
        seconds = int(t % 60)
        ts = f"{minutes}:{seconds:02d}"
        # Use on_screen_text as chapter label if available, else narration preview
        label = scene.on_screen_text.strip() or scene.narration[:40].strip()
        lines.append(f"{ts} — {label}")
        t += dur

    lines += [
        "",
        "— Auto-generated by ExamCracker AI",
    ]
    return "\n".join(lines)


def _post_pinned_comment(yt, video_id: str, text: str) -> str:
    """Post a comment to the video. Returns 'SUCCESS', 'FAILED (AUTH_SCOPE)', or 'FAILED'."""
    try:
        resp = yt.commentThreads().insert(
            part="snippet",
            body={
                "snippet": {
                    "videoId": video_id,
                    "topLevelComment": {
                        "snippet": {"textOriginal": text}
                    },
                }
            },
        ).execute()
        comment_id = resp["snippet"]["topLevelComment"]["id"]
        print(f"[upload] CTA comment posted (id={comment_id})")
        return "SUCCESS"
    except Exception as exc:
        msg = str(exc).lower()
        if "403" in msg and ("insufficient" in msg or "scope" in msg):
            print("[!] COMMENT: FAILED — AUTH_SCOPE (token lacks https://www.googleapis.com/auth/youtube.force-ssl; re-authorization required)")
            return "FAILED (AUTH_SCOPE)"
        print(f"[!] COMMENT: FAILED — {exc}")
        return "FAILED" 


def _ordered_projects(projects: list[YouTubeCredentials]) -> tuple[list[YouTubeCredentials], object]:
    """Return quota-eligible projects in the caller's preferred order."""
    if not projects:
        return [], None
    names = [p.name for p in projects]
    chosen_name, state = pick_project(names)
    if chosen_name is None:
        return [], state
    start = next(i for i, p in enumerate(projects) if p.name == chosen_name)
    return projects[start:] + projects[:start], state


def upload_video(
    video_path: Path,
    script: Script,
    projects: list[YouTubeCredentials],
    privacy: str = "public",
    category_id: str = "27",
    scene_durations: list[float] | None = None,
) -> dict:
    """Upload with automatic per-channel fallback.

    Each YouTube OAuth credential represents an independent channel/account.
    The upload itself is the failover boundary: if one credential fails before a
    video ID is created (including uploadLimitExceeded, quota, auth, or transport
    errors), the next quota-eligible credential is tried. Once a video ID is
    created, thumbnail/comment operations stay on that same channel and remain
    non-fatal.
    """
    ordered, state = _ordered_projects(projects)
    if not ordered:
        raise RuntimeError(
            "All YouTube projects are unavailable or exhausted: "
            "no quota-eligible credential remains."
        )

    body = {
        "snippet": {
            "title": script.title[:100],
            "description": script.description[:4900],
            "tags": script.tags[:15],
            "categoryId": category_id,
        },
        "status": {
            "privacyStatus": privacy,
            "selfDeclaredMadeForKids": False,
        },
    }

    failures: list[str] = []
    for chosen in ordered:
        creds = _creds_from_payload(chosen.payload)
        try:
            print(f"[upload] trying {chosen.name} (channel credential fallback)")
            yt = build("youtube", "v3", credentials=creds, cache_discovery=False)
            media = MediaFileUpload(
                str(video_path),
                mimetype="video/mp4",
                resumable=True,
                chunksize=4 * 1024 * 1024,
            )
            request = yt.videos().insert(part="snippet,status", body=body, media_body=media)
            response = None
            while response is None:
                _, response = request.next_chunk()

            video_id = response["id"]
            record_upload(chosen.name, state)
            url = f"https://youtu.be/{video_id}"
            print(f"[upload] video live: {url} via {chosen.name}")

            # Once YouTube returned a video ID, do not switch channels: the video
            # already exists on this channel. Metadata/thumbnail/comment failures
            # remain non-fatal.
            time.sleep(6)
            thumb_path = OUT_DIR / "thumbnail.jpg"
            _set_thumbnail(yt, video_id, thumb_path)

            can_post_comment = any("force-ssl" in s for s in (creds.scopes or []))
            comment_text = (script.pinned_comment or "").strip()
            comment_status = "SKIPPED (AUTH_SCOPE)"
            if can_post_comment:
                if comment_text:
                    comment_status = _post_pinned_comment(yt, video_id, comment_text)
                elif scene_durations:
                    comment_status = _post_pinned_comment(yt, video_id, _build_timestamp_comment(script, scene_durations))
            else:
                print("[upload] Pinned comment skipped: OAuth credentials only have 'youtube.upload' scope. (Re-authorize token with force-ssl scope if you want automated comments).")

            print(f"[upload summary] UPLOAD: SUCCESS | VIDEO: {url} | CHANNEL_CRED: {chosen.name} | COMMENT: {comment_status}")
            return {
                "video_id": video_id,
                "url": url,
                "project": chosen.name,
            }
        except Exception as exc:
            msg = str(exc).replace("\n", " ")[:1000]
            failures.append(f"{chosen.name}: {msg}")
            print(f"[!] {chosen.name} upload failed — trying next channel credential: {msg}")
            continue

    raise RuntimeError("All YouTube credentials failed: " + " | ".join(failures))
