"""YouTube Data API v3 uploader with thumbnail upload + pinned comment.

After a successful video upload this module:
  1. Sets the thumbnail (if thumbnail.jpg exists in OUT_DIR)
  2. Posts a pinned comment with scene timestamps
  3. Pins that comment via the YouTube API

All post-upload steps are non-fatal — a failure in any of them does not
abort the pipeline or count as a failed upload.
"""
from __future__ import annotations

import time
from pathlib import Path

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

from .config import YouTubeCredentials, OUT_DIR
from .quota import pick_project, record_upload
from .script_gen import Script


def _creds_from_payload(payload: dict) -> Credentials:
    return Credentials(
        token=payload.get("token"),
        refresh_token=payload["refresh_token"],
        token_uri=payload.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=payload["client_id"],
        client_secret=payload["client_secret"],
        scopes=payload.get(
            "scopes",
            [
                "https://www.googleapis.com/auth/youtube.upload",
                "https://www.googleapis.com/auth/youtube.force-ssl",
            ],
        ),
    )


def _set_thumbnail(yt, video_id: str, thumb_path: Path) -> None:
    """Upload thumbnail JPEG. Requires channel verification for custom thumbnails."""
    if not thumb_path.exists() or thumb_path.stat().st_size < 5000:
        print("[upload] no thumbnail file — skipping")
        return
    try:
        media = MediaFileUpload(str(thumb_path), mimetype="image/jpeg")
        yt.thumbnails().set(videoId=video_id, media_body=media).execute()
        print(f"[upload] thumbnail uploaded: {thumb_path.name}")
    except Exception as exc:
        print(f"[!] Thumbnail upload failed (non-fatal): {exc}")


def _build_timestamp_comment(script: Script, durations: list[float]) -> str:
    """Build a pinned comment with per-scene timestamps."""
    lines = [f"📚 {script.title}", ""]
    t = 0.0
    for i, (scene, dur) in enumerate(zip(script.scenes, durations)):
        minutes = int(t // 60)
        seconds = int(t % 60)
        ts = f"{minutes}:{seconds:02d}"
        # Use on_screen_text as chapter label if available, else narration preview
        label = scene.on_screen_text.strip() or scene.narration[:40].strip()
        lines.append(f"{ts} — {label}")
        t += dur

    lines += [
        "",
        "— Auto-generated by ExamCracker AI",
    ]
    return "\n".join(lines)


def _post_pinned_comment(yt, video_id: str, text: str) -> None:
    """Post a comment and pin it to the top of the comments section."""
    try:
        # Insert comment thread
        resp = yt.commentThreads().insert(
            part="snippet",
            body={
                "snippet": {
                    "videoId": video_id,
                    "topLevelComment": {
                        "snippet": {"textOriginal": text}
                    },
                }
            },
        ).execute()

        comment_id = resp["snippet"]["topLevelComment"]["id"]

        # Pin the comment
        yt.comments().setModerationStatus(
            id=comment_id,
            moderationStatus="published",
        ).execute()

        print(f"[upload] pinned comment posted (id={comment_id})")
    except Exception as exc:
        print(f"[!] Pinned comment failed (non-fatal): {exc}")


def upload_video(
    video_path: Path,
    script: Script,
    projects: list[YouTubeCredentials],
    privacy: str = "public",
    category_id: str = "27",
    scene_durations: list[float] | None = None,
) -> dict:
    names = [p.name for p in projects]
    chosen_name, state = pick_project(names)
    if chosen_name is None:
        raise RuntimeError(
            "All YouTube projects have exhausted their daily quota "
            "(10,000 units each; 1,600 per upload = 6 uploads/day each)."
        )

    chosen = next(p for p in projects if p.name == chosen_name)
    creds = _creds_from_payload(chosen.payload)
    yt = build("youtube", "v3", credentials=creds, cache_discovery=False)

    body = {
        "snippet": {
            "title": script.title[:100],
            "description": script.description[:4900],
            "tags": script.tags[:15],
            "categoryId": category_id,
        },
        "status": {
            "privacyStatus": privacy,
            "selfDeclaredMadeForKids": False,
        },
    }

    media = MediaFileUpload(
        str(video_path),
        mimetype="video/mp4",
        resumable=True,
        chunksize=4 * 1024 * 1024,
    )

    request = yt.videos().insert(part="snippet,status", body=body, media_body=media)
    response = None
    while response is None:
        _, response = request.next_chunk()

    video_id = response["id"]
    record_upload(chosen.name, state)
    url = f"https://youtu.be/{video_id}"
    print(f"[upload] video live: {url}")

    # Small pause so YouTube indexes the video before we post metadata
    time.sleep(3)

    # Optimization #1: Set thumbnail
    thumb_path = OUT_DIR / "thumbnail.jpg"
    _set_thumbnail(yt, video_id, thumb_path)

    # Optimization #5: Post pinned timestamp comment
    if scene_durations:
        comment_text = _build_timestamp_comment(script, scene_durations)
        _post_pinned_comment(yt, video_id, comment_text)

    return {
        "video_id": video_id,
        "url": url,
        "project": chosen.name,
    }
